export const EVENTS = {
    INITIAL_LOAD:          "INITIAL_LOAD",
    
    PROJECTS_LIST_LOADED:   "PROJECTS_LIST_LOADED",
    PROJECT_SELECTED:       "PROJECT_SELECTED",
    PROJECT_OPEN_REQUESTED: "PROJECT_OPEN_REQUESTED",
    PROJECT_OPENED:         "PROJECT_OPENED",

    MODAL_CLOSE_REQUESTED: "MODAL_CLOSE_REQUESTED",
    MODAL_CLOSED:          "MODAL_CLOSED",

    MODAL_OPEN_PROJECT_REQUESTED: "MODAL_OPEN_PROJECT_REQUESTED",

    MENU_CLOSE_REQUESTED:  "MENU_CLOSE_REQUESTED",
    MENU_OPEN_REQUESTED:   "MENU_OPEN_REQUESTED"
};